config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'placements#index'
  resources :placements, only: [:index, :show, :update]
  resources :classrooms do
    member do
      get 'populate'
      post 'populate'
    end
    resources :placements, only: [:index, :create]
  end

  # Authentication
  get '/auth/:provider/callback', to: 'users#auth_callback', as: 'auth_callback'
  get '/logout', to: 'users#logout', as: 'logout'

  get '/sheets', to: 'sheets#index', as: 'sheets'
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  has_many :students
  has_many :rankings, through: :students
  has_many :companies
  has_many :placements
  has_many :pairings, through: :placements
  belongs_to :creator, class_name: "User"

  # WARNING: extremely destructive!!!
  def purge()
    self.placements.each do |p|
      p.pairings.destroy_all
    end
    self.placements.destroy_all
    self.students.each do |s|
      s.rankings.destroy_all
    end
    self.companies.destroy_all
    self.students.destroy_all
  end

  def from_spreadsheets(interview_results, student_preferences)
    errors = []

    if interview_results.keys.sort != student_preferences.keys.sort
      raise Spreadsheet::SpreadsheetError("Mismatch in students between interview results and student_preferences")
    end

    # Transactions rollback on exceptions, so we need to
    # use the bang (!) versions of DB methods
    self.transaction do
      self.purge()

      # Build student records
      student_names = interview_results.keys

      student_names.each do |name|
        self.students.create!(name: name)
      end

      # Build company records
      company_names = []
      interview_results.each do |student_name, interviews|
        interviews.each do |company_name, results|
          company_names << company_name
        end
      end
      company_names.uniq!

      company_names.each do |name|
        self.companies.create!(name: name)
      end

      # Build ranking records
      student_names.each do |student_name|
        student = self.students.find_by(name: student_name)
        interviews = interview_results[student_name]
        preferences = student_preferences[student_name]

        if interviews.keys.sort != preferences.keys.sort
          errors << "Student #{student_name} has mismatch between interview companies #{interviews.keys} and preference companies #{preferences.keys}"
          next
        end

        interviews.keys.each do |company_name|
          company = self.companies.find_by(name: company_name)
          interview = interviews[company_name]
          preference = preferences[company_name]
          Ranking.create!(
            student: student,
            company: company,
            interview_result: interview['score'],
            interview_result_reason: interview['reason'],
            student_preference: preference)
        end
      end

      # Figure out how many internship slots each company has
      self.companies.each do |company|
        company.slots = company.rankings.count / self.interviews_per_slot + 1
        company.save!
      end

      if errors.length > 0
        error_text = "Encountered errors while building classroom records:"
        errors.each do |error|
          error_text += "\n" + error
        end
        raise Spreadsheet::SpreadsheetError.new(error_text)
      end
    end
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :require_login
  before_action :find_classroom, except: [:index, :new, :create]

  def index
    @classrooms = Classroom.all
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.creator = @current_user

    if @classroom.save
      flash[:status] = :success
      flash[:message] = "created classroom #{@classroom.id}"
      redirect_to classroom_path(@classroom)

    else
      flash[:status] = :failure
      flash[:message] = "could not create classroom"
      flash[:errors] = @classroom.errors.messages
      render :new

    end
  end

  def show
  end

  def edit
  end

  def update
    @classroom.update_attributes(classroom_params)

    if @classroom.save
      flash[:status] = :success
      flash[:message] = "updated classroom #{@classroom.id}"
      redirect_to classroom_path(@classroom)

    else
      flash[:status] = :failure
      flash[:message] = "could not update classroom"
      flash[:errors] = @classroom.errors.messages
      render :edit

    end
  end

  def destroy
    # TODO DPR: destroy all placements
    @classroom.destroy
    redirect_to classrooms_path
  end

  def populate
    # flash[:status] = :failure
    # flash[:message] = "Not yet implemented"
    # redirect_to classroom_path(params[:classroom_id])
    interview_sheet = InterviewResultSpreadsheet.new(@classroom.interview_result_spreadsheet, @current_user)
    interviews = interview_sheet.populate

    student_sheet = StudentPreferenceSpreadsheet.new(@classroom.student_preference_spreadsheet, @current_user)
    preferences = student_sheet.populate

    @classroom.from_spreadsheets(interviews, preferences)

    # render :populate
    redirect_to classroom_path(@classroom)
  end

private
  def classroom_params
    params.require(:classroom).permit(:name, :interview_result_spreadsheet, :student_preference_spreadsheet, :interviews_per_slot)
  end

  def find_classroom
    @classroom = Classroom.find_by(id: params[:id])
    if @classroom.nil?
      render file: "public/404.html", status: :not_found
    end
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<section>
  <%= form_for @classroom do |f| %>
    <%= f.label :name, "Classroom name" %>
    <%= f.text_field :name %>

    <%= f.label :interviews_per_slot %>
    <%= f.number_field :interviews_per_slot %>

    <section>
      <h3>Finding Spreadsheet IDs</h3>
      <%= image_tag "spreadsheet_id.png", alt: "How to find a spreadsheet's ID" %>

      <%= f.label :interview_result_spreadsheet %>
      <%= f.text_field :interview_result_spreadsheet %>

      <%= f.label :student_preference_spreadsheet %>
      <%= f.text_field :student_preference_spreadsheet %>
    </section>

    <%= f.submit class: "button" %>
  <% end %>
</section>

app/views/classrooms/edit.html.erb
<h2>Edit Classroom <%= @classroom.name %></h2>
<%= render partial: "form" %>

app/views/classrooms/index.html.erb
<h2>Classroom List</h2>

<section class="button-group">
  <%= link_to "Add a new Classroom", new_classroom_path, class: "button" %>
</section>

<table>
  <thead>
    <tr>
      <td>Name</td>
      <td>Students</td>
      <td>Companies</td>
      <td>Placements</td>
      <td>New Placement</td>
      <td>Added</td>
      <td>Added By</td>
    </tr>
  </thead>
  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= link_to classroom.name, classroom_path(classroom) %></td>
        <td><%= classroom.students.count %></td>
        <td><%= classroom.companies.count %></td>
        <td><%= link_to "#{classroom.placements.count}", classroom_placements_path(classroom), class: "button" %></td>
        <td>
          <%= link_to "Blank", classroom_placements_path(classroom, run_solver: false), method: :post, class: "button" %>
          <%= link_to "Filled", classroom_placements_path(classroom, run_solver: true), method: :post, class: "button" %>
        </td>
        <td><%= classroom.created_at %></td>
        <td><%= classroom.creator.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/classrooms/new.html.erb
<h2>Add a new Classroom</h2>
<%= render partial: "form" %>

app/views/classrooms/populate.html.erb
<h2>Interview Results</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Result</th>
      <th>Reason</th>
    </tr>
  </thead>
  <tbody>
    <% @interview_results.each do |student, results| %>
      <% results.each do |company, result| %>
        <tr>
          <td><%= student %></td>
          <td><%= company %></td>
          <td><%= result[:score] %></td>
          <td><%= result[:reason] %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<h2>Student Rankings</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Ranking</th>
    </tr>
  </thead>
  <tbody>
    <% @student_ranks.each do |student, rankings| %>
      <% rankings.each do |company, rank| %>
        <tr>
          <td><%= student %></td>
          <td><%= company %></td>
          <td><%= rank %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/classrooms/show.html.erb
<div class="row">
  <section class="columns large-9 small-12">
    <h2><%= @classroom.name %></h2>
    <p>Added <%= @classroom.created_at %> by <%= @classroom.creator.name %></p>

    <p>Interview results spreadsheet: <%= link_to @classroom.interview_result_spreadsheet || "Not Set", "https://docs.google.com/spreadsheets/d/#{@classroom.interview_result_spreadsheet}" %></p>
    <p>Student ranking spreadsheet: <%= link_to @classroom.student_preference_spreadsheet || "Not Set", "https://docs.google.com/spreadsheets/d/#{@classroom.student_preference_spreadsheet}" %></p>

    <p>Interviews per internship slot: <%= @classroom.interviews_per_slot %></p>
  </section>

  <section class="button-group columns large-3 small-12">
    <%= link_to "Classroom List", classrooms_path, class: "button" %>
    <%= link_to "Edit Classroom", edit_classroom_path(@classroom), class: "button" %>
    <%= link_to "Delete Classroom", classroom_path, method: :delete, data: { confirm: "This will destroy all placements for this classroom! Are you absolutely sure?" }, class: "alert button" %>
  </section>
</div>

<div class="row">
  <% if @classroom.students.count == 0 && @classroom.companies.count == 0 %>
    <p>
      Looks like this classroom's data hasn't been loaded yet.
      <%= button_to "Load from spreadsheets", populate_classroom_path(@classroom), class: "button" %>
    </p>

  <% else %>
    <p>
      <%= button_to "Reload from spreadsheets", populate_classroom_path(@classroom), class: "warning button" %>
      Warning: this will destroy any existing placements for this classroom!
    </p>

    <section class="columns small-12">
      <h3><%= @classroom.placements.count %> Placements</h3>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Students Placed</th>
            <th>Score</th>
            <th>Created By</th>
            <th>Last Modified</th>
          </tr>
        </thead>
        <tbody>
          <% @classroom.placements.each do |placement| %>
            <tr>
              <td><%= link_to placement.name ? placement.name : placement.id, placement_path(placement) %></td>
              <td><%= placement.pairings.count %> of <%= @classroom.students.count %></td>
              <td><%= placement.score %></td>
              <td>TODO DPR</td>
              <td><%= placement.created_at %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>

    <section class="columns large-6 small-12">
      <h3><%= @classroom.students.count %> Students</h3>
      <table>
        <thead>
          <tr>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <% @classroom.students.each do |student| %>
            <tr>
              <td><%= student.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>

    <section class="columns large-6 small-12">
      <h3><%= @classroom.companies.count %> Companies</h3>
      <table>
        <thead>
          <tr>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <% @classroom.companies.each do |company| %>
            <tr>
              <td><%= company.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>

    <section class="columns small-12">
      <h3><%= @classroom.rankings.count %> Rankings</h3>
      <table>
        <thead>
          <tr>
            <th>Student</th>
            <th>Company</th>
            <th>Student Preference</th>
            <th>Interview Result</th>
            <th>Interview Comments</th>
          </tr>
        </thead>
        <tbody>
          <% @classroom.students.each do |student| %>
            <% student.rankings.each_with_index do |ranking, i| %>
              <tr>
                <td><%= i == 0 ? student.name : "" %></td>
                <td><%= ranking.company.name %></td>
                <td><%= ranking.student_preference %></td>
                <td><%= ranking.interview_result %></td>
                <td><%= ranking.interview_result_reason %></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </section>
  <% end %>
</div>