config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'placements#index'
  resources :placements, only: [:index, :show, :update]
  resources :classrooms do
    member do
      get 'populate'
      post 'populate'
    end
    resources :placements, only: [:index, :create]
  end

  # Authentication
  get '/auth/:provider/callback', to: 'users#auth_callback', as: 'auth_callback'
  get '/logout', to: 'users#logout', as: 'logout'

  get '/sheets', to: 'sheets#index', as: 'sheets'
end

app/models/placement.rb
class Placement < ApplicationRecord
  belongs_to :classroom
  has_many :pairings
  has_many :students, through: :classroom
  has_many :companies, through: :classroom

  # Replace all pairings for this placement
  #
  # new_pairings should be an array of pairings, of form
  #   [ { company_id: 123, student_id: 456 }, ... ]
  #
  # If new_pairings is omitted, all current pairings
  #   will be destroyed.
  #
  # Will rollback and throw an ActiveRecord::RecordInvalid
  #   if any of the pairings is invalid.
  #
  # Returns an ActiveRecord::Collection representing
  #   this placement's pairings
  def set_pairings(new_pairings=[])
    self.transaction do
      self.pairings.destroy_all
      new_pairings.each do |pair|
        # AR will rollback when an exception is thrown
        self.pairings.create! pair
      end
    end
    return self.pairings
  end

  def self.build(options)
    p = self.new(options)
    unless p.name
      p.name = Faker::Food.ingredient
    end
    return p
  end

  def score
    sum = 0
    self.pairings.each do |pairing|
      ranking = Ranking.find_by(student_id: pairing.student_id, company_id: pairing.company_id)
      if ranking
        sum += ranking.student_preference * ranking.interview_result
      end
    end
    return sum
  end

  def solve
    puts "About to generate solution for pairing #{self.name} for classroom #{self.classroom.name} with #{self.classroom.students.count} students and #{self.classroom.companies.count} companies"

    start_time = Time.now
    solver = Solver.new(self.classroom)
    pairings = solver.solve
    end_time = Time.now

    self.transaction do
      # Clear out any existing pairings
      # TODO DPR: handle solving the remainder of a pairing
      self.pairings.destroy_all

      # Add all the generated pairings to this placement
      pairings.each do |pair|
        pair.placement = self
        pair.save!
      end
    end

    puts "Generated #{pairings.length} pairings with total score #{self.score} in #{Time.now - start_time} seconds, #{solver.iterations} iterations"
  end
end

app/controllers/placements_controller.rb
class PlacementsController < ApplicationController
  before_action :find_placement, only: [:show, :update]

  def index
    @classrooms = Classroom.all
    @placements = Placement.all

    # If the request was for a particular classroom, filter for it
    @classroom_id = params[:classroom_id]
  end

  def create
    @placement = Placement.build(classroom_id: params[:classroom_id])
    if @placement.save()
      if params[:run_solver]
        @placement.solve
      end
      redirect_to placement_path(@placement)
    else
      flash[:status] = :failure
      flash[:message] = "Could not create placement"
      flash[:errors] = @placement.errors.messages
      redirect_back
    end
  end

  def show
  end

  def update
    begin
      @placement.set_pairings(placement_update_params['pairings'])

      puts "Transaction success!"
      render json: {
        errors: []
      }
    rescue ActiveRecord::RecordInvalid => invalid
      puts "Rendering bad request"
      render status: :bad_request, json: {
        errors: invalid.record.errors.messages
      }
    end
  end

private
  def find_placement
    begin
      @placement = Placement.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render status: :not_found, content: false
    end
  end

  def placement_update_params
    params.require(:placement).permit(pairings: [:company_id, :student_id])
  end
end

app/helpers/placements_helper.rb
module PlacementsHelper
end

app/views/placements/index.html.erb
<div id="placement-chooser" class="row">
  <header id="placement-chooser-toolbar" class="row">
    <h2 class="large-7 columns">
      Click a placement to go to the workbench
    </h2>

    <div class="large-5 columns">
      <%= select_tag "classroom",
          options_from_collection_for_select(@classrooms, :id, :name, @classroom_id),
          include_blank: "All Classrooms",
          id: "classroom-select",
          class: "large-6 columns"
      %>
      <div class="button-group large-6 columns">

        <button class="button" id="toolbar-filter-button">
          Filter
        </button>
        <%= link_to "New", "javascript: void(0)", method: :post, class: "button", id: "toolbar-new-button" %>
      </div>
    </div>
  </header>

  <ul id="placement-list" class="row">
  </ul>
</div>



<!-- Underscore templates are set to use #
     instead of %, to not conflict with ERB -->
<script type="text/template" id="placement-card-template">
  <div class="placement-container">
    <a href="<#- url #>">
      <h3>
        Placement <#- name ? name : id #>
      </h3>
      <p>
        Classroom: <#- classroom_name #>
      </p>
      <p>
        <#- pairing_count #> of <#- student_count #> students paired
      </p>
      <p>
        Last modified <#- updated_at #>
      </p>
    </a>
  </div>
</script>



<!-- This all is ERB, not Underscore -->
<script type="text/javascript" id="initial-data">
  window.placementList = [
    <% @placements.each do |placement| %>
      {
        id: <%= placement.id %>,
        name: "<%= placement.name %>",
        updated_at: "<%= placement.updated_at %>",
        classroom_id: <%= placement.classroom_id %>,
        classroom_name: "<%= placement.classroom.name %>",
        student_count: <%= placement.classroom.students.length %>,
        pairing_count: <%= placement.pairings.length %>,
        url: "<%= placement_path(placement) %>"
      },
    <% end %>
  ]
</script>

app/views/placements/show.html.erb
<header class="clearfix">
  <h2 class="float-left">
    Placement
    <% if @placement.name %>
      <em><%= @placement.name %></em>
      (<%= @placement.id %>)
    <% else %>
      <%= @placement.id %>
    <% end %>
    for <%= link_to @placement.classroom.name, classroom_path(@placement.classroom) %>
  </h2>

  <nav class="float-right button-group" id="toolbar">
    <button class="success button" id="toolbar-save-button">
      Save
    </button>
    <button class="button" id="toolbar-undo-button">
      Undo
    </button>
    <button class="button" id="toolbar-redo-button">
      Redo
    </button>
  </nav>
</header>

<section id="placement-workbench">
  <header id="workbench-toolbar">
  </header>

  <section class="large-9 columns">
    <ul id="companies" class="row">
    </ul>
  </section>

  <aside id="unplaced-students" class="large-3 columns">
  </aside>

  <footer id="bus-details">
  </footer>
</section>

<!-- Initial placement state
Note: the double equals on the ERB tag prevents HTML escaping,
which we don't really want for a big blob of JSON
-->
<script type="text/javascript" id="placement-data">
  window.placementData = <%== render partial: "placement" %>
</script>

<!-- Underscore templates -->
<script type="text/template" id="company-template">
  <div class="company">
    <h3>
      <#- name #>
    </h3>
    <ul class="student-list">
    </ul>
  </div>
</script>

<script type="text/template" id="student-template">
  <div class="row" draggable="true">
    <h4 class="large-9 columns">
      <#- name #>
    </h4>
    <# if (score) { #>
      <h4 class="large-3 columns student-score">
        (<#- score #>)
      </h4>
    <# } #>
  </div>
</script>

<script type="text/template" id="empty-slot-template">
  <li class='empty student'>
    <h4>
      &nbsp;
    </h4>
  </li>
</script>

<script type="text/template" id="bus-details-template">
  <div>
    <p>
      Current Score:
      <#- score #>,
      Selected:
      <#- student ? student.get('name') : "[None]" #>
    </p>
  </div>
</script>