config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'placements#index'
  resources :placements, only: [:index, :show, :update]
  resources :classrooms do
    member do
      get 'populate'
      post 'populate'
    end
    resources :placements, only: [:index, :create]
  end

  # Authentication
  get '/auth/:provider/callback', to: 'users#auth_callback', as: 'auth_callback'
  get '/logout', to: 'users#logout', as: 'logout'

  get '/sheets', to: 'sheets#index', as: 'sheets'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Internship Placer" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png'%>
  </head>

  <body>
    <nav class="top-bar">
      <div class="top-bar-title">
        <strong><%= link_to "Ada Internship Placer", root_path %></strong>
      </div>
      <div>
        <div class="top-bar-left">
          <ul class="dropdown menu" data-dropdown-menu>
            <li><%= link_to "Placements", placements_path %></li>
            <li><%= link_to "Classrooms", classrooms_path %></li>
          </ul>
        </div>
        <div class="top-bar-right">
          <ul class="menu">
            <% if @current_user %>
              <li>Logged in as <%= @current_user.name %></li>
              <li><%= link_to "Log Out", logout_path, id: "toolbar-logout-button" %></li>
            <% else %>
              <li>Not logged in</li>
              <li><%= link_to "Log In", "/auth/google_oauth2", id: "toolbar-login-button" %></li>
            <% end %>
        </div>
      </div>
    </nav>

    <% if flash[:errors] or flash[:message] %>
      <section class="row status <%= flash[:status] %>">
        <h3><%= flash[:status] == :failure ? "A problem occurred: " : "" %><%= flash[:message] %></h3>
        <% if flash[:errors] %>
          <ul>
            <% flash[:errors].each do |name, problems| %>
              <% problems.each do |problem| %>
                <li><%= name %>: <%= problem %></li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      </section>
    <% end %>

    <main>
      <%= yield %>
    </main>

    <footer class="clearfix">
      <p class="float-left">&copy; <%= link_to "Ada Developers Academy", "http://adadevelopersacademy.org/" %>, 2017</p>
      <p class="float-right">Find a bug? Want to request a feature? <%= link_to "Find us on GitHub", "https://github.com/droberts-ada/interview-placement-app" %></p>
  </body>
</html>